### ISSUE TITLE
Missing version in filename and possibly outdated

### ISSUE THREAD

**Issue by FriedrichFroebel** [ivan-hc/Skype-appimage#1]
Thanks for bundling. Unfortunately, the latest builds seem to have no version number inside their filenames anymore, which makes it hard to check whether my local version still is the latest. It seems like the currently distributed version is 8.109.0.209.

As far as I can see, the request to https://repo.skype.com/deb/dists/stable/main/binary-amd64/Packages times out/receives an error code "504 Gateway Time-out".

According to https://www.skype.com/en/get-skype/download-skype-for-desktop/ and https://answers.microsoft.com/en-us/skype/forum/all/download-the-deb-installation-file-for-debian/73b4fea5-736c-4513-9422-b331d77c4343, the DEB package currently used by the AppImage is no longer maintained/supported with only the Snap being provided in the latest version 8.119.0.201: https://snapcraft.io/skype

**Comment by ivan-hc** [comment]
hi, you're right, I've just downloaded the .deb package and extaxted it
```
wget https://go.skype.com/skypeforlinux-64.deb
```
version 8.109.0.209

-------------------------------------

if the .deb package is no more provided, this is a problem. A serious problem. We may no more have an AppImage for this.

@Samueru-sama I know you use it

**Comment by ivan-hc** [comment]
anyway, since the app is based on Electron, we can try to extract the Snap an get only what its needed

can you provide a way to download the snap package? I must look into it.

**Comment by ivan-hc** [comment]
this is the content of my Appimage

![Istantanea_2024-06-28_17-48-43 png](https://github.com/ivan-hc/Skype-appimage/assets/88724353/9ce32216-96f9-44e6-ab94-7ec300a59e26)

it is not much

**Comment by FriedrichFroebel** [comment]
Unfortunately, I do not have any experience with Snap packages and no distribution with them enabled, thus I do not really know how to download the underlying files in this case.

**Comment by FriedrichFroebel** [comment]
I just did some research and apparently the following provides us with the actual package content:

1. Get the metadata and download link with curl: `curl -H 'Snap-Device-Series: 16' http://api.snapcraft.io/v2/snaps/info/skype --silent | jq '.'` (https://askubuntu.com/questions/1075694/how-to-get-snap-download-url)
2. Choose the download URL from the channel with the amd64 architecture and the name "stable", https://api.snapcraft.io/api/v1/snaps/download/QRDEfjn4WJYnm0FzDKwqqRZZI77awQEV_348.snap in my case.
3. Download the file.
4. A Snap file apparently is a SquashFS file as well, thus we can unpack it with `unsquashfs file.snap`, which creates the `squashfs-root` directory. (https://askubuntu.com/questions/1162798/how-do-i-view-the-contents-of-a-snap-file)
5. Looking into `squashfs-root/usr/share/skypeforlinux`, it seems like this is the actual package as in your screenshot, although I have not further tested it.

![Screenshot_20240628_190003](https://github.com/ivan-hc/Skype-appimage/assets/7279752/67f65ac3-73e5-45e8-a58c-4b803c50505d)

**Comment by FriedrichFroebel** [comment]
The Flatpak package has a one-liner for getting the download URL as well: https://github.com/flathub/com.skype.Client?tab=readme-ov-file#updating-skype-client-flatpak

**Comment by ivan-hc** [comment]
@FriedrichFroebel install squashfs-tools on your system and run this script into an empty directory
```
#!/bin/sh

APP=skype

# TEMPORARY DIRECTORY
mkdir -p tmp
cd ./tmp || exit 1

# DOWNLOAD APPIMAGETOOL
if ! test -f ./appimagetool; then
	wget -q "$(wget -q https://api.github.com/repos/probonopd/go-appimage/releases -O - | sed 's/"/ /g; s/ /\n/g' | grep -o 'https.*continuous.*tool.*86_64.*mage$')" -O appimagetool
	chmod a+x ./appimagetool
fi

# DOWNLOAD THE SNAP PACKAGE
if ! test -f ./*.snap; then
	wget -q "$(curl -H 'Snap-Device-Series: 16' http://api.snapcraft.io/v2/snaps/info/skype --silent | sed 's/[()",{} ]/\n/g' | grep "^http" | head -1)"
fi

# EXTRACT THE SNAP PACKAGE AND CREATE THE APPIMAGE
unsquashfs -f ./*.snap
mkdir -p "$APP".AppDir
VERSION=$(cat ./squashfs-root/*.yaml | grep "^version" | head -1 | cut -c 10-)
mv ./squashfs-root/usr/share/skypeforlinux/* ./"$APP".AppDir/
mv ./squashfs-root/usr/share/pixmaps/skypeforlinux.png ./"$APP".AppDir/
mv ./squashfs-root/snap/gui/skypeforlinux.desktop ./"$APP".AppDir/
sed -i 's#${SNAP}/meta/gui/skypeforlinux.png#skypeforlinux#g; s#Network;Application;##g' ./"$APP".AppDir/*.desktop

cat >> ./"$APP".AppDir/AppRun << 'EOF'
#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"
export UNION_PRELOAD="${HERE}"
exec "${HERE}"/skypeforlinux "$@"
EOF
chmod a+x ./"$APP".AppDir/AppRun

ARCH=x86_64 VERSION=$(./appimagetool -v | grep -o '[[:digit:]]*') ./appimagetool -s ./"$APP".AppDir
cd ..
mv ./tmp/*.AppImage ./Skype-"$VERSION"-x86_64.AppImage
```
few second and the Snap-based AppImage is ready, but I need to know if it works, I don't use Skype from 20 years

**Comment by ivan-hc** [comment]
https://github.com/ivan-hc/Skype-appimage/assets/88724353/6e665bb4-7807-4923-bbe7-a200bd238fe1

**Comment by ivan-hc** [comment]
as you can see from the video I get a lot of errors about a missing service. I need to know if we can ignore this.

**Comment by ivan-hc** [comment]
but I can see that also my AppImage hosted here shows same errors

![Istantanea_2024-06-28_22-04-55](https://github.com/ivan-hc/Skype-appimage/assets/88724353/6d61d689-6b56-4ed0-b515-cb9745640ccb)

I'll upload this Snap-based AppImage, so you can test directly from here

**Comment by ivan-hc** [comment]
Download it from https://github.com/ivan-hc/Skype-appimage/releases/tag/continuous and close if this solves the issue

**Comment by FriedrichFroebel** [comment]
Thanks for the updated AppImage. I am able to successfully start the application, login and see the list of calls with the same log output as before, thus it seems to work. If I really experience further issues, I am going to open another issue here for further analysis/discussions.
